Creation of header toolbar molecule component
jorgecarmona/next-hr-suite pull request #14
Opened 2024-06-05 20:55 UTC by napito27

## HeaderToolbar

![Screenshot 2024-06-05 164058](https://github.com/jorgecarmona/next-hr-suite/assets/137454549/4b8e2667-a29f-42c2-a2e9-a018702fc2f0)

## Stories

![Screenshot 2024-06-05 164028](https://github.com/jorgecarmona/next-hr-suite/assets/137454549/e2dc60d1-4f1b-4223-aeb2-fbd9fb5a9288)

2024-06-05 22:53 UTC, NancyBlancoS approved these changes
Buen trabajo!

2024-06-07 15:34 UTC, SGutierrez17 commented on packages/next-hr-fe/src/__tests__/molecules/header-toolbar.test.tsx
> +      <HeaderToolbar
Ingeniero Napo, el componente no recibe children, arregla ahí.

2024-06-07 15:34 UTC, SGutierrez17 commented on packages/next-hr-fe/src/__tests__/molecules/header-toolbar.test.tsx
> +    const button1 = screen.getByRole('button', {name: /my requests/i});
ingeniero este test esta haciendo lo mismo que el anterior, por lo tanto no lo veo necesario.

2024-06-07 15:38 UTC, SGutierrez17 requested changes
Ingeniero Napo buenos días! te hice unos comentarios para que los revises, además tienes conflictos por solucionar.

2024-06-07 20:39 UTC, napito27 commented on packages/next-hr-fe/src/__tests__/molecules/header-toolbar.test.tsx
> +    const button1 = screen.getByRole('button', {name: /my requests/i});
Ing. la diferencia es que el test anterior solo muestra la lista de botones, y esta test muestra la lista con uno de los botones seleccionados.

2024-06-17 23:56 UTC, jorgecarmona approved these changes

2024-06-17 23:56 UTC, NancyBlancoS approved these changes

2024-06-18 00:03 UTC, SGutierrez17 approved these changes
Good Job!

2024-06-18 00:09 UTC, merged