Updated header toolbar
jorgecarmona/next-hr-suite pull request #35
Opened 2024-06-25 03:28 UTC by napito27

2024-06-25 04:05 UTC, SGutierrez17 commented on packages/next-hr-fe/src/stories/molecules/header-toolbar.stories.tsx
> +};
Ingeniero te recomiendo usar el satisfies

2024-06-25 04:06 UTC, SGutierrez17 commented on packages/next-hr-fe/src/stories/molecules/header-toolbar.stories.tsx
agrega tambien el action del click

2024-06-25 04:07 UTC, SGutierrez17 commented on packages/next-hr-fe/src/stories/molecules/header-toolbar.stories.tsx
> +import type {Meta} from '@storybook/react';
ingeniero nosotros importamos meta de la siguiente manera:
import {Meta} from "@storybook/react";

2024-06-25 04:11 UTC, SGutierrez17 commented on packages/next-hr-fe/src/__tests__/molecules/header-toolbar.test.tsx
>      expect(button3).toBeInTheDocument();
ingeniero este test es correcto? porque esperas ver el button3 y estas creando la const de button1...

2024-06-25 04:12 UTC, SGutierrez17 requested changes
Ingeniero te deje comentarios

2024-06-25 12:17 UTC, napito27 commented on packages/next-hr-fe/src/stories/molecules/header-toolbar.stories.tsx
Ingeniero. el action no se lo agregue por que el componente no tiene un parametro `onClick`

2024-06-25 12:20 UTC, napito27 commented on packages/next-hr-fe/src/__tests__/molecules/header-toolbar.test.tsx
>      expect(button3).toBeInTheDocument();
si Ing. estoy creando una variable para cada boton y luego los busca todos (buttton1, button2, button3)

2024-06-26 19:16 UTC, paulagutierrez08 reviewed
Te deje un comentario ing

2024-06-26 19:16 UTC, paulagutierrez08 commented on packages/next-hr-fe/src/__tests__/molecules/header-toolbar.test.tsx
>      const button1 = screen.getByRole('button', {name: /my requests/i});
Ingeniero en esta const la nombraste como `button1` y estas esperando el `button3`, entiendo que estas buscando cualquiera de los botones. Te recomendaría llamar la constante más general. Ej `button`

2024-06-26 19:16 UTC, SGutierrez17 commented on packages/next-hr-fe/src/stories/molecules/header-toolbar.stories.tsx
ingeniero pero si estas pasando un onClick, que es el de boton, entonces podrias traer ese parametro, asi como se hizo en los otros componentes

2024-06-26 20:16 UTC, napito27 commented on packages/next-hr-fe/src/__tests__/molecules/header-toolbar.test.tsx
>      const button1 = screen.getByRole('button', {name: /my requests/i});
![image](https://github.com/jorgecarmona/next-hr-suite/assets/137454549/ae57ad38-297d-40ab-92f3-97f621c36e97)

disculpa Ing.  podrias mostrarme un scrrenshot del codigo que tu ves, el Ing, Sergio me dio e mismo comentario pero en el codigo que yo tengo estoy buscando los 3 botones yb por eso tengo 3 variables defaerentes

2024-06-26 21:21 UTC, paulagutierrez08 approved these changes

2024-06-26 21:21 UTC, paulagutierrez08 commented on packages/next-hr-fe/src/__tests__/molecules/header-toolbar.test.tsx
>      const button1 = screen.getByRole('button', {name: /my requests/i});
Ing acabo de darme cuenta que se tenían compiladas las demas líneas de texto. Es correcto como lo tienes

2024-06-26 21:41 UTC, ProiserSA approved these changes

2024-06-26 21:43 UTC, SGutierrez17 approved these changes

2024-06-26 22:21 UTC, merged