Feat(Passwordtexfield):control enablement in storybook
jorgecarmona/next-hr-suite pull request #38
Opened 2024-07-10 15:57 UTC by OskarMantilla21

![image](https://github.com/jorgecarmona/next-hr-suite/assets/137963398/50173e5a-a376-4d06-addd-26323082bd67)

2024-07-10 17:16 UTC, SGutierrez17 commented on packages/next-hr-fe/src/stories/atoms/password.stories.tsx
> +  args: {
Ingeniero faltan los otros args que estaban:
deberia quedar asi:

``
  args: {
    label: '',
    value: '',
    helperText: '',
    onChangeCallback: (value) => {
      console.log('Password entered:', value);
    },
    error: false,
    errorHelperText: '',
    fullWidth: false,
    icon: true,
    required: true,
  },
``

2024-07-10 17:16 UTC, SGutierrez17 requested changes
Ingeniero corrige lo siguiente

2024-07-11 15:16 UTC, NancyBlancoS approved these changes

2024-07-11 23:33 UTC, SGutierrez17 approved these changes

2024-07-12 19:30 UTC, closed without merging