NHR-17-Fix-Textfield-Component
jorgecarmona/next-hr-suite pull request #39
Opened 2024-07-10 16:35 UTC by juanav22

![image](https://github.com/jorgecarmona/next-hr-suite/assets/124211065/d87476d9-a303-4684-bcbf-a871789987ec)

2024-07-10 18:09 UTC, juanav22 commented
Assignment 1 is pending In the options, correct that the label is on the input

2024-07-10 18:36 UTC, SGutierrez17 commented on packages/next-hr-fe/src/stories/atoms/textField.stories.tsx
> +  tags: ['autodocs'],
Ingeniera te faltaron argumentos:
estos son todos:
![image](https://github.com/jorgecarmona/next-hr-suite/assets/136516495/9eee8e12-ed0b-4ba3-9b81-4bbce5a907e1)

2024-07-10 18:36 UTC, SGutierrez17 requested changes
Buenas tardes ingeniera juana te deje comentarios

2024-07-10 18:56 UTC, juanav22 commented on packages/next-hr-fe/src/stories/atoms/textField.stories.tsx
> +  tags: ['autodocs'],
ingeniero revisa bien estan todos

2024-07-10 19:22 UTC, SGutierrez17 approved these changes
Good job!

2024-07-10 20:24 UTC, napito27 commented on packages/next-hr-fe/src/stories/atoms/textField.stories.tsx
Ing. podrias revisar por que cambia el bgColor del helper text cuando le das click a read only
![Screenshot 2024-07-10 160549](https://github.com/jorgecarmona/next-hr-suite/assets/137454549/809af195-6d50-4470-b3aa-60c822937c0b)

tambien el label deberia mostrarse arriba del textfield
![Screenshot 2024-07-10 160456](https://github.com/jorgecarmona/next-hr-suite/assets/137454549/7ff856f6-8a88-4a12-8f16-b8f32f7a4cb4)

2024-07-10 20:40 UTC, juanav22 commented on packages/next-hr-fe/src/stories/atoms/textField.stories.tsx
ingeniero, lo que pasa es que si activas el readOnly te va a dar ese bagColor por default
![image](https://github.com/jorgecarmona/next-hr-suite/assets/124211065/59dbc215-46a4-4c01-9622-4bd4ff042ac8)

2024-07-10 20:44 UTC, juanav22 commented on packages/next-hr-fe/src/stories/atoms/textField.stories.tsx
![image](https://github.com/jorgecarmona/next-hr-suite/assets/124211065/f8522029-a632-4f5a-9f5e-82739d89d90e)

2024-07-11 20:11 UTC, napito27 reviewed
looks good Ing. i did also notice the icon inside the email input is an IconButton, and i dont think it needs to be. 
![image](https://github.com/jorgecarmona/next-hr-suite/assets/137454549/e061d25f-f3b6-4c69-9bf6-026751ef2dc4)

2024-07-11 20:28 UTC, napito27 approved these changes
looks good Ing. good job

2024-07-12 17:10 UTC, closed without merging