fix/NHR-31-Fix-Rename-Component-Password-Textfield
jorgecarmona/next-hr-suite pull request #62
Opened 2024-07-12 20:01 UTC by OskarMantilla21

2024-07-12 20:21 UTC, davidc0326 requested changes

2024-07-12 20:21 UTC, davidc0326 commented on packages/next-hr-fe/src/atoms/password.tsx
> +interface PasswordProps {
ingeniero revisaste si este codigo se puede simplificar como sugerio el Arquitecto.

2024-07-12 20:44 UTC, andrea-carmona approved these changes
Thanks so much, looks good.

2024-07-15 12:15 UTC, davidc0326 approved these changes

2024-07-16 15:00 UTC, merged